adding doctor feature
vladysllav/wellplan-fe pull request #18
Opened 2023-09-29 21:43 UTC by eugenchen

+to do:
Consider using a rich text editor for the description to allow for formatting.
Image uploads should be optimized for faster loading times when patients view the doctor's profile.

2023-09-30 09:26 UTC, YuriiSkyba1 requested changes

2023-09-30 09:26 UTC, YuriiSkyba1 commented on src/pages/AddDoctorPage/AddDoctorPage.tsx
> +const AddDoctorPage: React.FC = () => {
please use functions without React like in another components

2023-10-01 10:02 UTC, dadclak commented on src/pages/AddDoctorPage/AddDoctorForm.tsx
> +        setShowSuccessMessage(false);
why you don't use the toast for information for user?

2023-10-01 10:02 UTC, dadclak commented on src/pages/AddDoctorPage/AddDoctorForm.tsx
> +              <option value="" label="Select Specialization" />
you can generate this options by loop. And declare this data to const array then use here.

2023-10-01 10:02 UTC, dadclak commented on src/pages/LogSignPage/AuthorizationForm/AuthorizationForm.tsx
> +// import './AuthorizationForm.css';
you can delete this row

2023-10-02 05:54 UTC, YuriiSkyba1 commented
please fix conflicts

2023-10-02 10:57 UTC, eugenchen commented on src/pages/AddDoctorPage/AddDoctorForm.tsx
> +              <option value="" label="Select Specialization" />
changed

2023-10-02 11:00 UTC, eugenchen commented on src/pages/AddDoctorPage/AddDoctorPage.tsx
> +const AddDoctorPage: React.FC = () => {
changed

2023-10-02 11:06 UTC, eugenchen commented on src/pages/AddDoctorPage/AddDoctorForm.tsx
> +        setShowSuccessMessage(false);
changed

2023-10-02 11:07 UTC, eugenchen commented on src/pages/LogSignPage/AuthorizationForm/AuthorizationForm.tsx
> +// import './AuthorizationForm.css';
deleted

2023-10-02 11:08 UTC, eugenchen commented
@YuriiSkyba1 fixed

2023-10-02 15:52 UTC, YuriiSkyba1 approved these changes

2023-10-02 16:10 UTC, merged