footer
vladysllav/wellplan-fe pull request #2
Opened 2023-09-19 16:31 UTC by eugenchen

Added footer

2023-09-19 17:01 UTC, YuriiSkyba1 commented
please create branches in format like WEL-17-footer with ticket title

2023-09-19 17:02 UTC, YuriiSkyba1 commented
Aslo we can use this commits format [WEL-17]: implemented footer component

2023-09-19 17:10 UTC, YuriiSkyba1 requested changes

2023-09-19 17:10 UTC, YuriiSkyba1 commented on src/components/Footer/facebook.svg
please move all images to assets folder /images

2023-09-19 17:10 UTC, YuriiSkyba1 commented on src/components/Footer/instagram.svg
please move all images to assets folder /images

2023-09-19 17:10 UTC, YuriiSkyba1 commented on src/components/Footer/logo.png
please move all images to assets folder /images

2023-09-19 17:10 UTC, YuriiSkyba1 commented on src/components/Footer/footer.tsx
> +      <ul id="footer-links">
You can split this to smaller components for example section nav menu and contacts and import these components to new Page/Footer

2023-09-19 17:10 UTC, YuriiSkyba1 commented on src/components/Footer/footer.css
> +.footer-menu {
you can use tailwind classes for styiling

2023-09-19 17:10 UTC, YuriiSkyba1 commented on src/components/Footer/footer.tsx
> +      <ul id="footer-rules">
using id it's bad approach please use classes instead id

2023-09-19 17:10 UTC, dadclak commented
> please create branches in format like WEL-17-footer with ticket title

@YuriiSkyba1 do we must add prefix 'feature' -> `feature/WEL-17` ?

2023-09-20 19:57 UTC, YuriiSkyba1 approved these changes

2023-09-20 21:18 UTC, YuriiSkyba1 approved these changes

2023-09-21 09:40 UTC, merged